config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/about' => 'welcome#about', as: :about
  get '/login' => 'sessions#new', as: :new_session
  get 'students/populate_branches'
  get 'students/:id/populate_branches' => 'students#populate_branches' 
  get 'jobposts/populate_branches'
  get 'jobposts/:id/populate_branches' => 'jobposts#populate_branches' 
  get 'jobposts/:id/view_applicants' => 'jobposts#view_applicants', as: :view_applicants_jobpost
  get 'jobposts/:id/download_excelsheet' => 'jobposts#download_excelsheet', as: :download_excelsheet_jobpost
  get '/populate_branches'  => 'jobposts#populate_branches'
  get 'jobposts/shortlist_applicant' => 'jobposts#shortlist_applicant'
  get 'jobposts/select_applicant' => 'jobposts#select_applicant'
  get 'students/:id/account_settings' => 'students#account_settings', as: :account_settings_student
  get 'students/:id/my_applications' => 'students#my_applications', as: :my_applications_student
  patch 'students/:id/account_settings' => 'students#update_account'
  get '/students/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_email_availability' => 'all_users#check_email_availability'
  get '/password_resets/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_college_name_availability' => 'tpos#check_college_name_availability'
  get '/tpos/:id/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/:id/check_college_name_availability' => 'tpos#check_college_name_availability'
  patch '/jobposts/:id/:tpo_note' => 'jobposts#tpo_note'

  resources :tpos
  resources :students
  resources :welcome
  resources :sessions
  resources :all_users
  resources :jobposts
  resources :locations
  resources :courses
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:edit, :new, :create, :update]

  delete 'logout' => 'sessions#destroy'
  post 'job_applications' => 'job_applications#create', as: :submit_application
  get '/job_feed' => 'students#job_feed', as: :jobfeed_student
  get '/student_search' => 'tpos#search_students', as: :search_students_tpo
  get '/admin_panel' => 'tpos#admin_panel', as: :admin_panel
  get 'jobposts/:id/print_applicants' => 'jobposts#print_applicants', as: :print_applicants_jobpost
  post '/tpos/activate_tpo' => 'tpos#activate_tpo', as: :activate_tpo

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/student.rb
require 'file_size_validator'

class Student < ActiveRecord::Base
	
	attr_accessor :remember_token, :reset_token, :activation_token, :image
	
  has_many :experiences, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :job_applications, dependent: :destroy
  has_many :jobposts, through: :job_applications
  has_one :social_profile, dependent: :destroy

  accepts_nested_attributes_for :social_profile, allow_destroy: true
  accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :experiences, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true

  mount_uploader :image, ImageUploader

	before_save { self.email = email.downcase.gsub(/\s+/, "") }

  before_save { self.first_name = first_name.strip.gsub(/\s+/, " ").titleize }

  before_save { self.last_name = last_name.strip.gsub(/\s+/, " ").titleize }

  after_commit :remove_previously_stored_image, on: :update
	
	before_create :update_all_users_table

  before_create :create_activation_digest
	
	validates :email, 
			       presence: true,
			       length: {minimum: 5},
			       format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
			       uniqueness: {case_sensitive: false}

	 validates :first_name, 
              presence: true,
              length: {minimum: 3, maximum: 15}

	validates :college_id, 
              presence: true, 
              numericality: true

	validates :branch_id, 
              presence: true, 
              numericality: true

  validates :percentage, 
              presence: true, 
              numericality: {less_than_or_equal_to: 100}

  validates :year_of_passing, 
              presence: true, numericality: {
                                              greater_than: 2010,
                                              less_than_or_equal_to: 2020}

  validates :phone_no, 
              numericality: true, 
              length: {maximum: 10, minimum: 8}, 
              on: :update_account, 
              allow_blank: true

  validates :password, 
              length: {minimum: 6, maximum: 15}, 
              allow_blank: true

  validates_format_of :image, 
                        :with => %r{\.(png|jpg|jpeg)\z}i, 
                        :message => "Only .png, .jpeg & .jpg extentions are allowed for images", 
                        on: :update_account

 validates :image, 
                :file_size => { 
                  :maximum => 1.megabytes.to_i 
                } 

	has_secure_password

	# Returns the hash digest of the given string.
	def Student.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
  	BCrypt::Password.create(string, cost: cost)
	end

	# generates a random token
	def Student.new_token
	 SecureRandom.urlsafe_base64  		
	end

  # Remembers a user in the database for use in persistent sessions.
	def remember
  	self.remember_token = Student.new_token
  	update_column(:remember_digest, Student.digest(remember_token))
	end

	def authenticated?(attribute, token)
		digest = self.send("#{attribute}_digest")
		return false if digest.nil?
  	BCrypt::Password.new(digest).is_password?(token)
	end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = Student.new_token
    update_attribute(:reset_digest,  Student.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def update_activation_digest
     self.activation_token = Student.new_token
     self.update_attribute(:activation_digest, Student.digest(activation_token))
     self.send_activation_email
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  	  # Forgets a user.
	def forget
		update_column(:remember_digest, nil)
	end

  def self.search_applicants(search, jobpost_id)
    where("first_name iLIKE?", "%#{search}%") |
    where("last_name iLIKE?", "%#{search}%") |
    where("email iLIKE?", '%#{search}%' ) 
  end

  def self.search(keyword, college_id)
    
    #where("email iLIKE ?", "#{keyword}") |
    #where("first_name iLIKE ?", "%#{keyword}%") |
    #where("last_name iLIKE ?", "%#{keyword}%") |
    #where("first_name || ' ' || last_name iLIKE ?", "%#{keyword}%")
    #where("cast(college_id as text) iLIKE ?", "#{college_id}") 
    #where("first_name+' '+last_name LIKE?", "%#{keyword}%")

    where("college_id = #{college_id} AND (email ilike '%#{keyword}%' OR first_name || ' ' || last_name ilike '%#{keyword}%' OR skills ilike '%#{keyword}%') ")
    
  end

    private

      def create_activation_digest
          self.activation_token = Student.new_token
          self.activation_digest = Student.digest(activation_token)
      end

        def update_all_users_table
            new_user = AllUser.new
            new_user.email = self.email
            new_user.first_name = self.first_name
            new_user.last_name = self.last_name
            new_user.college = self.college_id
            new_user.user_type = 2
            errors.add(:email, "is already taken") if !new_user.save
            new_user.save
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :update_account, :account_settings, :job_feed, :my_applications]
    before_action :correct_user, only: [:edit, :update, :account_settings, :my_applications]
    before_action :student_user, only: :job_feed
    before_action :redirect_if_logged_in, only: [:new, :create]
    before_action :admin_user, only: [:destroy, :index]

    include StudentsHelper

    def index
    	@students = Student.all
    end
	
	def new
		@colleges = College.all
		@student = Student.new
		@courses = Course.all
		@branches = Branch.where(course_id: Course.first.id)
	end

	def create
		@courses = Course.all
		@branches = Branch.where(course_id: params[:student][:course_id])
		@student = Student.new(student_params)
		@student.location_id = College.find(params[:student][:college_id]).location_id
		if @student.save
			#log_in @student
			@student.send_activation_email
			flash[:info] = "Please check your email to activate your account"
			redirect_to root_url 
		else
			render 'new'
		end
	end

	def show
		@student = Student.find(params[:id])
		@college = College.find(@student.college_id)
		@course = Course.find(@student.course_id)
		@branch = Branch.find(@student.branch_id)
		@location = Location.find(@student.location_id)
		@experiences = Experience.where(student_id: @student.id).order(end_date: :desc)
		@educations = Education.where(student_id: @student.id).order(year_of_passing: :desc)
		@projects = Project.where(student_id: @student.id)
		@current_students_tpo = Tpo.find_by(college_id: current_user.college_id)
	end

	def edit
		@student = current_user
		@colleges = College.where
		@branches = Branch.where(course_id: @student.course_id).order(name: 'ASC')
		@education = current_user.educations.build
		@social_profile = current_user.social_profile || current_user.build_social_profile
		#@existing_eduaction = Education.where(student_id: @student.id)
		#@education = Education.new
		@experience = current_user.experiences.build
		@project = current_user.projects.build
	end

	def update
		@branches = Branch.where(course_id: params[:student][:course_id])
		@student = current_user
		if @student.update_attributes(update_params)
			redirect_to current_user
			flash[:success] = "Profile successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		student = Student.find(params[:id])
		if student.destroy
			flash[:success] = "Student Deleted Successfully"
			redirect_to :back
		end
	end

	def update_account
		@student = Student.find(params[:id])
		if @student.update_attributes(account_params)
			flash[:success] = "Account updated Successfully"
			redirect_to root_path
		else
			render 'account_settings'
		end 
	end

	def populate_branches
		@branches = Branch.where(course_id: params[:course_id]).order(name: 'ASC')
		respond_to do |format|
			format.js
		end 
	end

	private
		def student_params
			params.require(:student).permit(:email, :password, :first_name, :last_name, :college_id,
											:course_id, :branch_id, :location_id, :percentage, :year_of_passing)
		end

		def account_params
			params.require(:student).permit(:password)
		end

		def update_params
			params.require(:student).permit(:first_name, :last_name, :location_id, :college_id, :course_id, :branch_id, :image, :phone_no, 
											:skills, :achievements, :percentage, :year_of_study, :year_of_passing, 
											:educations_attributes => [:id, :institute, :degree, :percentage, :year_of_passing, :_destroy], 
											:experiences_attributes => [:id, :company_name, :position, :contributions, :start_date, :end_date, :_destroy],
											:projects_attributes => [:id, :name, :description, :_destroy],
											:social_profile_attributes => [:id, :website, :linkedin, :github])
		end

		def correct_user
			@user = Student.find(params[:id])
			if !(@user == current_user)
				redirect_to root_path
				flash[:danger] = "Action not allowed as you're not the owner of requested profile"
			end
		end

		def student_user
			if current_user.user_type == 1
				redirect_to root_path
				flash[:danger] = "The feature is available fo students only"
			end 
		end

end

app/helpers/students_helper.rb
module StudentsHelper

	def account_settings
		@student = current_user
		@current_students_tpo = Tpo.find_by(college_id: current_user.college_id)
		@current_students_tpo = Tpo.find_by(college_id: current_user.college_id)
	end

	def my_applications
		student = Student.find(params[:id])
		@applications = student.job_applications.order(id: :desc)
	end

	def job_feed
		@student = current_user
		@current_students_tpo = Tpo.find_by(college_id: current_user.college_id)
		if params[:search]
	    	@jobposts = Jobpost.search(params[:search].gsub(/\s+/, ' ').strip)
	    elsif params[:location_id]
	    		@jobposts = Jobpost.where(location_id: params[:location_id])
	  	else
			job_type = params[:job_type]
			case job_type
				when '1'
					@jobposts = Jobpost.where(job_type: 1, tpo_id: @current_students_tpo.id)
				when '2'
					@jobposts = Jobpost.where(job_type: 2)
				when '3'
					@jobposts = Jobpost.where(job_type: 3, tpo_id: @current_students_tpo.id)
				when '4'
					@jobposts = Jobpost.where(job_type: 4)
				else
					@jobposts = Jobpost.where(  "(tpo_id = ?) OR (tpo_id != ? AND (job_type = ? OR job_type = ?) )",  @current_students_tpo.id, @current_students_tpo, 2, 3 )
			end
		end
		if params[:search]
			@jobposts = Kaminari.paginate_array(@jobposts.first(50)).page(params[:page])
		else
			@jobposts = [] if @jobposts.nil?
			@jobposts = @jobposts.page(params[:page]).per(50)
		end

	end
end

app/views/students/_education_form.html.erb
<div class="col-lg-12">
	<div class="heading_container">
		<h4>Education</h4>
	</div>
	<table class="table current_education">
		<thead>
			<tr>
				<th width="40%">College/Board</th>
				<th width="40%">Degree</th>
				<th width="5%">Percentage</th>
				<th width="12%">Year of Passing</th>
				<th width="2%" style="visibility:hidden">close</th>
			</tr>
		</thead>
		<tbody class="current_education_details">
			<td>
				<%= f.collection_select(:college_id, College.all.order(college_name: "ASC"), :id, :college_name, {}, {:class => "form-control"}) %>
			</td>
			<td>
				<%= f.collection_select(:course_id, Course.all.order(name: 'ASC'), :id, :name, {}, {:class => "course", :style => "width:50%", :onchange => "pop_branches()"}) %>
				<span class="ajax_overlay_container">
					<span class="ajax_overlay">
						<%= image_tag 'ajax-loader-blue.gif' %>
					</span>
					<%= f.collection_select(:branch_id, @branches, :id, :name, {}, {:class => "branch", :style => "width:48%"}) %>
				</span>
			</td>
			<td>
				<%= f.text_field :percentage, :class => "form-control", :placeholder => "%" %>
			</td>
			<td>
				<%= f.collection_select(:year_of_passing, BatchYear.all, :year, :year, {}, {:class => "form-control"}) %>
			</td>
		</tbody>
	</table>
	<table class="table prev_education">
		<tbody>
			<%= f.fields_for :educations, {:class=>"prev_education_details"} do |e| %>
				<%= f.hidden_field :education_ids, :multiple => true %>
				
					<tr>
						<td width="37%"><%= e.text_field :institute, :placeholder => "College/Board", :class => "form-control institute" %></td>
						<td width="37%"><%= e.text_field :degree, :placeholder => "UG/Secondary/High School", :class => "form-control degree" %></td>
						<td width="12%"><%= e.text_field :percentage, :placeholder => "%", :class => "form-control percentage" %></td>
						<td width="13%"><%= e.text_field :year_of_passing, :placeholder => "20XX", :class => "form-control year_of_passing" %></td>
						<td width="20%">
							<%= e.hidden_field :_destroy %>
							<a class="remove_edu_row btn btn-sm btn-danger">x</a>
						</td>
					</tr>
				
			<% end %>
		</tbody>
	</table>
	<p class="pull-left" id="degree_limit_reached">You cannot add more than 4 degrees.</p>
	<a class="btn bt-md blue pull-right" id="add_schools">
		<span class="fa fa-plus"></span> Add Schools/Colleges
	</a>
	<!--link_to "Add Courses/Colleges", f, :educations --> 
</div>

app/views/students/_experience_form.html.erb
<div class="heading_container">
	<h4>Experience<small>(Internships/Part-Time Jobs)</small></h4>
</div>
<div class="experience_container">
	<%= f.fields_for :experiences do |e| %>
		<%= f.hidden_field :experience_ids, :multiple => true %>
		<div class="experience">
			<div class="col-lg-6 col-md-6">
				<div class="input-group">
					<div class="input-group-addon"><span class="fa fa-building"></span></div>
					<%= e.text_field :company_name, :class => "form-control company_name", :placeholder => "Company" %>
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="input-group">
					<div class="input-group-addon"><span class="fa fa-briefcase"></span></div>
					<%= e.text_field :position, :class => "form-control position", :placeholder => "Position" %>
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="input-group">
					<div class="input-group-addon"><span class="fa fa-calendar-o"></span></div>
					<%= e.text_field :start_date, :class => "form-control date", :placeholder => "Start Date" %>
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="input-group">
					<div class="input-group-addon"><span class="fa fa-calendar"></span></div>
					<%= e.text_field :end_date, :class => "form-control date", :placeholder => "End Date" %>
				</div>
			</div>
			<div class=" col-lg-12">
				<div class="form-group">
					<%= e.label :contributions, :class => "control-label" %> 
					<%= e.text_area :contributions, :class => "form-control contributions" %>
				</div>
			</div>
			<div class="col-lg-12">
				<%= e.hidden_field :_destroy %>
				<a class="btn btn-md btn-danger pull-right" id="remove_experience">
					<span class="fa fa-remove"></span> Remove
				</a>
			</div>
		</div>
	<% end %>
</div>
<p id="experience_limit_reached">You cannot add more than 6 experiences</p>
<a class="pull-right btn btn-md blue" id="add_experience"><span class="fa fa-plus"></span> Add More</a>

app/views/students/_project_form.html.erb
<div class="heading_container">
	<h4>Projects<small></small></h4>
</div>
<div class="project_container">
	<%= f.fields_for :projects do |e| %>
		<%= f.hidden_field :project_ids, :multiple => true %>
		<div class="project">
			<div class="col-lg-12">
				<div class="input-group">
					<div class="input-group-addon"><span class="fa fa-file-code-o"></span></div>
					<%= e.text_field :name, :class => "form-control project_name", :placeholder => "Name of Project" %>
				</div>
			</div>
			<div class=" col-lg-12">
				<div class="form-group">
					<%= e.label :description, :class => "control-label" %> 
					<%= e.text_area :description, :class =>"form-control" %>
				</div>
			</div>
			<div class="col-lg-12">
				<%= e.hidden_field :_destroy %>
				<a id="remove_project" class="btn btn-danger btn-md pull-right"><span class="fa fa-remove"></span> Remove</a> 
			</div>
		</div>
	<% end %>
</div>
<p id="project_limit_reached">You cannot add more than 6 Projects</p>
<a class="pull-right btn btn-md blue" id="add_project"><span class="fa fa-plus"></span> Add Project</a>

app/views/students/_student_sidebar.html.erb
<div class="col-lg-2 col-md-2 col-sm-2 user_content_wrapper student_sidebar hidden-xs">
	<div class="user_pic_container">
		<div class="user_pic" style="background:url('<%= @student.image_url.nil? ? image_url('default_user.jpg') : image_url(@student.image_url.to_s) %>')">

		</div>
	</div>
	<div class="text-center">
		<% if @student == current_user %>
			<%= link_to student_path(@student), :class => "user_name" do %>
				<%= current_user.first_name %> <%= current_user.last_name %>
				<% end %>
			<%= link_to my_applications_student_path(id: current_user.id), :class => "btn btn-block blue" do %>
				<span class="fa fa-list-ul"></span> My Applications
			<% end %>
			<%= link_to @current_students_tpo, :class => "btn btn-block btn-success green" do %>
				<span class="fa fa-eye"></span> Visit TPO
			<% end %>
		<% else %>
			<a href="#" class="user_name"><%= @student.first_name %> <%= @student.last_name %></a>
			<div class="student_contact_info">
				<!--<span class="divider"></span>
				<p><span class="fa fa-envelope"></span></p>
				<span class="divider"></span>
				<p><span class="fa fa-phone"></span> 9876543210<br/></p>
				<span class="divider"></span>-->
				<div class="student_web_links">
					<% unless @student.social_profile.nil? %>
						<% unless @student.social_profile.website.blank? %>
							<a href="<%= @student.social_profile.website %>" class="btn btn-sm" target="_blank"><span class="fa fa-globe"></span></a>
						<% end %>
						<% unless @student.social_profile.github.blank? %>
							<a href="<%= @student.social_profile.github %>" class="btn btn-sm" target="_blank"><span class="fa fa-github-square"></span></a>
						<% end %>
						<% unless @student.social_profile.linkedin.blank? %>
							<a href="<%= @student.social_profile.linkedin %>" class="btn btn-sm" target="_blank"><span class="fa fa-linkedin-square"></span></a>
						<% end %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/students/index.html.erb
<% provide(:title, 'All Students') %>
<h1 class="text-center">
  All Students
  <small>
    [<%= pluralize(@students.count, " Student")+" from " %>
    <%= pluralize(@students.pluck('DISTINCT college_id').length, " College") %>]
  </small>
</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email ID</th>
      <th>College</th>
      <th>Course</th>
      <td>Actions</td>
    </tr>
  </thead>
  <% @students.each do |student| %>
    <% college = College.find(student.college_id) %>
    <% course = Course.find(student.course_id) %>
    <tr>
      <td><%= link_to student.first_name+" "+student.last_name, student_path(student) %></td>
      <td><%= student.email %></td>
      <td><%= college.college_name %></td>
      <td><%= course.name %></td>
      <% if current_user.admin? %>
    	 <td><%= link_to "delete", student, method: :delete, data: { confirm: "You sure?" } %></td>
  	  <% end %>
    </tr>
  <% end %>
</table>

app/views/students/job_feed.html.erb
<% provide(:title, "JobFeed | "+@student.first_name.to_s+" "+@student.last_name.to_s) %>
<div class="row">
	<%= render 'student_sidebar' %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<% if params[:search] %>
			<p class="lead text-center">Search Results For - <%= params[:search] %></p>
		<% end %>
		<% if @jobposts.any? %>
			<div class="pagination_container">
		  		<%= paginate @jobposts, :window => 0 %>
			</div>
		  <ul class="list-unstyled jobposts_list">
		    <%= render @jobposts %>
		  </ul>
		  <% else %>
		  	<div class="no_posts_note">
			  	<p class="lead">We cannot find any suitable jobs for you please come back later.</p>
			</div>
		<% end %>
	</div>
</div>

app/views/students/new.html.erb
<% provide(:title, "Student SignUp") %>
<div class="intro_wrapper window_span">
    <div class="intro_wrapper_overlay window_span"></div>
    <div class="container">
        <div class="signup_form_container student_signup form_container curr_active">
            <div class="signup_form form_content animated fadeIn">
            	<p>SignUp as Student</p>
                <%= form_for(@student) do |f| %>
                    <%= render 'shared/stu_error_messages' %>
                    <div class="form-group">
                        <%= f.label :email, :class => "control-label" %>
                        <%= f.text_field :email, :class => "form-control", :placeholder => "Eg.: username@example.com" %>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :first_name, :class => "control-label" %>
                                <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :last_name, :class => "control-label" %>
                                <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :college_id, :class => "control-label" %>
                        <%= f.collection_select(:college_id, College.all.order(college_name: "ASC"), :id, :college_name, {}, {:class=>'form-control'}) %>
                    </div>
                    <div class="row">
                    	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        	<div class="form-group">
                                <%= f.label :course_id, :class => "control-label" %>
                                <%= f.collection_select :course_id, @courses, :id, :name, {}, {:class=>"form-control branches_dropdown", :onchange=>"pop_branches()"} %>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        	<div class="form-group">
                                <%= f.label :branch_id, :class => "control-label" %>
                                <div class="ajax_overlay_container">
                                    <div class="ajax_overlay">
                                        <%= image_tag 'ajax-loader-white.gif' %>
                                    </div>
                                    <%= f.collection_select :branch_id, @branches, :id, :name, {}, {:class=>"form-control"} %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :percentage, :class => "control-label" %>
                                <%= f.text_field :percentage, :class => "form-control", :placeholder=>"% in above course till now" %>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :year_of_passing, :class => "control-label" %>
                                <%= f.collection_select(:year_of_passing, BatchYear.all, :year, :year, {}, {:class => "form-control"}) %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :password, :class => "control-label" %>
                        <%= f.password_field :password, :class => "form-control", :placeholder => "Your Profile Password", :autocomplete => "off" %>
                    </div>
                    <div class="redirect_links">
                    	<%= link_to "SignUp as College", new_tpo_path %> | 
                        <%= link_to "Already Signed Up?", new_session_path %>
                    </div>
                    <div class="submit_btn_wrapper btn btn-lg"><span style="visibility:hidden">Sign Up</span>
                        <%= f.submit "Sign Up", :class => "btn btn-default btn-lg sign_up_btn" %>
                        <span class="hover_span"></span>
                    </div>
                <% end %>
           </div>
        </div>
   </div>
</div>
<%= javascript_include_tag 'student_users' %>