config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/about' => 'welcome#about', as: :about
  get '/login' => 'sessions#new', as: :new_session
  get 'students/populate_branches'
  get 'students/:id/populate_branches' => 'students#populate_branches' 
  get 'jobposts/populate_branches'
  get 'jobposts/:id/populate_branches' => 'jobposts#populate_branches' 
  get 'jobposts/:id/view_applicants' => 'jobposts#view_applicants', as: :view_applicants_jobpost
  get 'jobposts/:id/download_excelsheet' => 'jobposts#download_excelsheet', as: :download_excelsheet_jobpost
  get '/populate_branches'  => 'jobposts#populate_branches'
  get 'jobposts/shortlist_applicant' => 'jobposts#shortlist_applicant'
  get 'jobposts/select_applicant' => 'jobposts#select_applicant'
  get 'students/:id/account_settings' => 'students#account_settings', as: :account_settings_student
  get 'students/:id/my_applications' => 'students#my_applications', as: :my_applications_student
  patch 'students/:id/account_settings' => 'students#update_account'
  get '/students/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_email_availability' => 'all_users#check_email_availability'
  get '/password_resets/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_college_name_availability' => 'tpos#check_college_name_availability'
  get '/tpos/:id/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/:id/check_college_name_availability' => 'tpos#check_college_name_availability'
  patch '/jobposts/:id/:tpo_note' => 'jobposts#tpo_note'

  resources :tpos
  resources :students
  resources :welcome
  resources :sessions
  resources :all_users
  resources :jobposts
  resources :locations
  resources :courses
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:edit, :new, :create, :update]

  delete 'logout' => 'sessions#destroy'
  post 'job_applications' => 'job_applications#create', as: :submit_application
  get '/job_feed' => 'students#job_feed', as: :jobfeed_student
  get '/student_search' => 'tpos#search_students', as: :search_students_tpo
  get '/admin_panel' => 'tpos#admin_panel', as: :admin_panel
  get 'jobposts/:id/print_applicants' => 'jobposts#print_applicants', as: :print_applicants_jobpost
  post '/tpos/activate_tpo' => 'tpos#activate_tpo', as: :activate_tpo

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/jobpost.rb
class Jobpost < ActiveRecord::Base

	default_scope -> { order(created_at: :desc) }

	belongs_to :tpo

	has_many :eligible_courses, dependent: :destroy
	has_many :courses, through: :eligible_courses

	has_many :eligible_branches, dependent: :destroy
	has_many :branches, through: :eligible_branches

	has_many :job_applications, dependent: :destroy
	has_many :students, through: :job_applications 

	validates :tpo_id, presence: true, numericality: true

	validates :location_id, presence: true, numericality: true

	validates :company, presence: true

	validates :position, presence: true

	validates :percentage_required, presence: true, numericality: {less_than_or_equal_to: 100}

	#validates :eligible_courses, presence: true

	validates :venue, presence: true

	validates :last_date, presence: true

	validates :drive_date, presence: true

	validates :year_required, presence: true, numericality: true

	validates :reporting_time, presence: true

	validates_presence_of :courses

	def send_jobpost_mailer
		JobpostUpdate.new_job_posted(self).deliver_now
	end

	def send_application_status_mailer(student_id, status)
		JobpostUpdate.application_update(self, student_id, status).deliver_now
	end

	def send_tpo_note_mailer(applicants)
		JobpostUpdate.tpo_note(self, applicants).deliver_now
	end	

	def self.search(search)
	  where("company iLIKE ?", "%#{search}%") |
	  where("position iLIKE ?", "%#{search}%") |
	  where("venue iLIKE ?", "%#{search}%") |
	  where("job_profile iLIKE ?", "%#{search}%") |
	  where("other_requirements iLIKE ?", "%#{search}%") |
	  where("company || ' ' || position iLIKE?", "%#{search}%") |
	  where("position || ' ' || company iLIKE?", "%#{search}%") 
	end

end

app/controllers/jobposts_controller.rb
class JobpostsController < ApplicationController
	
	before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :show, :view_applicants, :select_applicant, :shortlist_applicant,
										 :print_applicants,:download_excelsheet]
	
	before_action :correct_user, only: [:destroy, :edit, :view_applications, :select_applicant, :shortlist_applicant, :print_applicants,
										:download_excelsheet]
	
	before_action :admin_user, only: :index

	include JobpostsHelper

	def index
		@jobposts = Jobpost.all
	end
	
	def new
		@tpo = current_user
		@jobpost = Jobpost.new
		@courses = Course.all
		@branches = Branch.all
	end

	def create
		@tpo = current_user
		@jobpost = current_user.jobposts.build(jobpost_params)
		@courses = Course.all
		@branches = Branch.all
		if @jobpost.save
			@jobpost.send_jobpost_mailer
			flash[:success] = "Job Posted Successfully. An email has been sent to eligible students of your college notifying them about the opportunity"
			redirect_to current_user
		else
			render 'new'
		end
	end

	def show
		current_user.user_type == 2 ? @student = current_user : @tpo = current_user
		@jobpost = Jobpost.find(params[:id])
		job = Jobpost.find(params[:id])
		@colege = College.find(Tpo.find(@jobpost.tpo_id).college_id)
		if current_user.user_type == 2
			@current_students_tpo = Tpo.find_by(college_id: current_user.college_id)
		end
	end

	def edit
		@tpo = current_user
		@jobpost = Jobpost.find(params[:id])
		@jobpost.last_date = @jobpost.last_date.strftime('%a, %d %b %Y')
		@jobpost.drive_date = @jobpost.drive_date.strftime('%a, %d %b %Y')
		@courses = Course.all
		@branches = Array.new
		@jobpost.course_ids.each do |c|
			eligible_branches = Branch.where(course_id: c)
				eligible_branches.each do |b|
					@branches.push(b)
				end
		end
		@previously_saved_course_ids = @jobpost.course_ids
		@previously_saved_course_ids = [] if @previously_saved_course_ids.nil?
		#byebug
	end

	def update
		@tpo = current_user
		@jobpost = Jobpost.find(params[:id])
		@courses = Course.all
		@branches = Array.new
		@jobpost.course_ids.each do |c|
			eligible_branches = Branch.where(course_id: c)
			eligible_branches.each do |b|
				@branches.push(b)
			end
		end
		@previously_saved_course_ids = @jobpost.course_ids
		@previously_saved_course_ids = [] if @previously_saved_course_ids.nil?
		if @jobpost.update_attributes(jobpost_params)
			flash[:success] = "Job Post Updated"
      		redirect_to @jobpost
		else
			render 'edit'
		end
	end

	def destroy
		Jobpost.find(params[:id]).destroy
		flash[:success] = "Jobpost Deleted."
		redirect_to root_path
	end

	def populate_branches
		@branches = Branch.where(course_id: params[:course_id])
		respond_to do |format|
			format.js
		end
	end

	private
		def jobpost_params
			params.require(:jobpost).permit(:company, :position, :percentage_required, :required_brach,:other_requirements, :ctc,  
											:job_profile, :location, :venue, :location_id, :job_type, :instructions, :year_required, 
											:about_company, :last_date, :drive_date, :reporting_time, :course_ids => [], :branch_ids => [])
		end

		def correct_user
			if params[:id]
				jobpost = Jobpost.find(params[:id])
			elsif params[:jobpost_id]
				jobpost = Jobpost.find(params[:jobpost_id])
			end
			@user = current_user
			if !(@user == Tpo.find(jobpost.tpo_id))
				flash[:danger] = "Action not allowed as you're not the author of the Jobpost."
				redirect_to root_path 
			end
	end

end

app/helpers/jobposts_helper.rb
module JobpostsHelper
	
	def search_applicants(search, jobpost)
		keywords = search.split
		students = Array.new
		keywords.each do |keyword|
			keyword = keyword.downcase
			student_ids = Student.where("lower(first_name) = ? OR lower(last_name) = ? OR email = ?", keyword, keyword, keyword).ids
			students.push(student_ids).flatten!
		end
		jobpost.job_applications.where(student_id: students)
	end

	def view_applicants
		@jobpost = Jobpost.find(params[:id])
		@show_selected = params[:show_selected]
		@show_shortlisted = params[:show_shortlisted]
		@search = params[:search_applicant]
		if params[:search_applicant]
			#students = Student.search_applicants(params[:search], params[:id])
			@applications = search_applicants(params[:search_applicant], @jobpost) 
		elsif @show_selected
			@applications = @jobpost.job_applications.where(selected: true)
		elsif @show_shortlisted
			@applications = @jobpost.job_applications.where(shortlisted: 1)
		else
			@applications = @jobpost.job_applications
		end
		@applications = [] if @applications.nil?
		#@applications = @applications.page(params[:page]).per(50)
	end

	def print_applicants
		@jobpost = Jobpost.find(params[:id])
		if params[:selected]
			@applications = @jobpost.job_applications.where(selected: true)
		elsif params[:shortlisted]
			@applications = @jobpost.job_applications.where(shortlisted: 1)
		else
			@applications = @jobpost.job_applications
		end
		@applications = [] if @applications.nil?
	end

	def download_excelsheet
		@jobpost = Jobpost.find(params[:id])
		if params[:selected]
			@applications = @jobpost.job_applications.where(selected: true)
		elsif params[:shortlisted]
			@applications = @jobpost.job_applications.where(shortlisted: 1)
		else
			@applications = @jobpost.job_applications
		end
		@applications = [] if @applications.nil?
		@applicant_ids = @applications.pluck(:student_id)
		respond_to do |format| 
			if params[:selected]
	       		format.xlsx {render xlsx: 'download_excelsheet', filename: "selected_"+@jobpost.company+"_"+@jobpost.position+"_applicants"}
	       	elsif params[:shortlisted]
	       		format.xlsx {render xlsx: 'download_excelsheet', filename: "shortlisted_"+@jobpost.company+"_"+@jobpost.position+"_applicants"}
	    	else
	    		format.xlsx {render xlsx: 'download_excelsheet', filename: "all_"+@jobpost.company+"_"+@jobpost.position+"_applicants"}
	    	end
	       		
	    end
	end

	def already_applied?
		jobpost = Jobpost.find(params[:id])
		student = current_user
		applied = JobApplication.find_by(student_id: student.id, jobpost_id: jobpost.id)
		!applied.nil?
	end

	def can_apply?
		jobpost = Jobpost.find(params[:id])
		author = Tpo.find(jobpost.tpo_id)
		student = current_user
		if jobpost.job_type == 1 || jobpost.job_type == 4
			student.college_id == author.college_id
		else
			return true
		end
	end

	def job_expired?
		jobpost = Jobpost.find(params[:id])
		Date.today > jobpost.last_date
	end

	def is_eligible?
		student = current_user
		student_course = student.course_id
		student_branch = student.branch_id
		student_percentage = student.percentage
		student_batch = student.year_of_passing
		j = Jobpost.find(params[:id])
		eligible_courses = j.course_ids
		eligible_branches = j.branch_ids
		eligible_percentage = j.percentage_required
		eligible_batch = j.year_required
		student_percentage >= eligible_percentage && eligible_courses.include?(student_course) && eligible_branches.include?(student_branch) && student_batch == eligible_batch
	end

	def shortlist_applicant
		applicant_id = params[:applicant_id]
		jobpost_id = params[:jobpost_id]
		@jobpost = Jobpost.find(jobpost_id)
		job_application = JobApplication.find_by(student_id: applicant_id, jobpost_id: jobpost_id)
		shortlisted_for_round = job_application.shortlisted
		shortlisted_for_round += 1
		respond_to do |format|
			if job_application.update_attribute(:shortlisted, shortlisted_for_round)
				@jobpost.send_application_status_mailer(applicant_id, "shortlisted")
				format.html { render :nothing => true, :notice => 'Update SUCCESSFUL!' } 
			end
		end
	end

	def select_applicant
		applicant_id = params[:applicant_id]
		jobpost_id = params[:jobpost_id]
		@jobpost = Jobpost.find(jobpost_id)
		job_application = JobApplication.find_by(student_id: applicant_id, jobpost_id: jobpost_id)
		respond_to do |format|
			if job_application.update_attribute(:selected, true)
				job_application.update_attribute(:shortlisted, 1)
				@jobpost.send_application_status_mailer(applicant_id, "selected")
				format.html { render :nothing => true, :notice => 'Update SUCCESSFUL!' } 
			end
		end
	end

	def tpo_note
		all = params[:all]
		shortlisted = params[:shortlisted]
		selected = params[:selected]
		jobpost = Jobpost.find(params[:id])
		jobpost.update(params.require(:jobpost).permit(:notification_mailer))
		if all
			applications = jobpost.job_applications
		elsif shortlisted && selected
			applications = jobpost.job_applications.where("shortlisted = 1 OR selected = true")
		elsif shortlisted
			applications = jobpost.job_applications.where(shortlisted: 1)
		elsif selected
			applications = jobpost.job_applications.where(selected: 1)
		else
			flash[:danger] = "Please select recipients for your message"
			redirect_to :back
		end
		applicants=Array.new
		applications.each do |a|
			applicant = Student.find(a.student_id)
			applicants.push(applicant)
		end
		jobpost.send_tpo_note_mailer(applicants)
		flash[:success] = "Mail sent to #{applications.count} applicant(s)"
		redirect_to :back
	end
	
end

app/views/jobposts/_jobpost.html.erb
<li id="jobpost-<%= jobpost.id %>" class="jobpost_container">
	<div class="jobpost">
		<div class="job_title">
			<div class="position left_aligned lead"><%= jobpost.position %></div>
			<div class="company right_aligned lead"><%= jobpost.company %></div>
		</div>
		<div class="job_info row">
			<div class="col-lg-3 col-md-3 col-sm-12 general_info">
				<ul class="lsit list-unstyled">
					<li>
						<span class="fa fa-map-marker"></span> 
						<%= Location.find(jobpost.location_id).location %>
					</li>
					<li>
						<span class="fa fa-suitcase"></span> 
						<%= JobType.find(jobpost.job_type).name %>
					</li>
					<li>
						<span class="fa  fa-minus-square"></span> 
						<%= jobpost.percentage_required %> %
					</li>
				</ul>
			</div>
			<div class="col-lg-9 col-md-9 col-sm-9 courses_branches">
				<ul class="list list-unstyled">
					<% jobpost.courses.each do |c| %>
						<% eligible_branches = Array.new %>
                        <li>
                        	<span class="course_name"><%= c.name %></span>
                        	<% c.branches.each do |b| %>
                        		<% eligible_branches.push(b) if jobpost.branch_ids.include?(b.id) %>
                        	<% end %>
                        	<% eligible_branches.each do |b| %>
                        		<span class="branch_name"><%= b.name %></span>
                        	<% end %>
                        </li>
                    <% end %>
				</ul>
			</div>
		</div>
		<div class="actions">
			<% if current_user.user_type == 1 && current_user.id == jobpost.tpo_id %>
				<%= link_to view_applicants_jobpost_path(id: jobpost.id), :class => "btn btn-default btn-sm pull-left" do %>
					<span class="fa fa-th-list"></span> View Applications
				<% end %>
				<%= link_to jobpost_path(jobpost), method: "delete", data: { confirm: "Are you sure you want to delete this post?" }, :class => "btn btn-danger btn-sm" do %>
					<span class="fa fa-close"></span> Delete
				<% end %>
				<%= link_to edit_jobpost_path(jobpost), :class => "btn btn-primary btn-sm" do %>
					<span class="fa fa-edit"></span> Edit
				<% end %>
				<%= link_to jobpost, :class => "btn blue btn-sm" do %>
					<span class="fa fa-eye"></span> View
				<% end %>   
			<% elsif current_user.user_type == 2 %>
				<%= link_to jobpost, :class => "btn blue btn-md" do %>
					<span class="fa fa-eye"></span> <%= JobApplication.find_by(student_id: current_user.id, jobpost_id: jobpost.id) ? "View" : "View & Apply" %>
				<% end %> 
			<% else %>
				<%= link_to jobpost, :class => "btn blue btn-sm" do %>
					<span class="fa fa-eye"></span> View
				<% end %>  
			<% end %> 
		</div>
		<div class="author">
			<% jobpost_author = jobpost.tpo %>
			posted <%= time_ago_in_words(jobpost.created_at) %> ago by <%= current_user == jobpost.tpo ? "you" : link_to(jobpost_author.first_name, jobpost_author)  %>
		</div>
	</div>
</li>

app/views/jobposts/edit.html.erb
<% provide(:title, "Edit Jobpost | "+current_user.first_name.to_s+" "+current_user.last_name.to_s) %>
<div class="row">
	<%= render '/tpos/tpo_sidebar' %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<div class="jobpost_form_container">
			<h3>Edit Job Post</h3>
				<%= render 'jobpost_form' %>
		</div> 
	</div>
</div>

app/views/jobposts/index.html.erb
<% provide(:title, 'All Jobposts') %>
<h1 class="text-center">All Jobposts<small>[<%= pluralize(@jobposts.count, " Jobpost") %>]</small></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Company and Position</th>
      <th>Applications</th>
      <td>Actions</td>
    </tr>
  </thead>
  <% @jobposts.each do |jobpost| %>
    <tr>
      <td><%= jobpost.id %></td>
      <td><%= link_to jobpost.company+" at "+jobpost.position, jobpost_path(jobpost) %></td>
      <td><%= jobpost.job_applications.count %></td>
      <% if current_user.admin? %>
    	 <td><%= link_to "delete", jobpost, method: :delete, data: { confirm: "You sure?" } %></td>
  	  <% end %>
    </tr>
  <% end %>
</table>

app/views/jobposts/new.html.erb
<% provide(:title, "Post a Job | "+current_user.first_name.to_s+" "+current_user.last_name.to_s) %>
<div class="row">
	<%= render '/tpos/tpo_sidebar' %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<div class="jobpost_form_container">
			<h3>Post an opportunity</h3>
				<%= render 'jobpost_form' %>
		</div> 
	</div>
</div>

app/views/jobposts/populate_branches.js.erb
$('.branches_selection .dynamic_branches_container').append('<div class="branches"></div>');
$('.branches_selection .dynamic_branches_container .branches:last').append('<b class="course_name"><%= @branches.first.course.name %></b>');
<% @branches.each do |branch| %>
	$('.branches_selection .dynamic_branches_container .branches:last').append('<label class="checkbox-inline"></label>');
	$('.branches_selection .dynamic_branches_container .branches label:last').append('<%= check_box_tag "jobpost[branch_ids][]", branch.id, false, {:id => dom_id(branch), :class => branch.id, "data-course"=>branch.course_id} %><%= label_tag dom_id(branch), branch.name %>');
<% end %>

app/views/jobposts/print_applicants.html.erb
<% provide(:title, "Students List | "+@jobpost.company+" | "+@jobpost.position) %>
<% if @applications.any? %>
	<p class="text-center">
		Students 
		<% if params[:selected] %>
			selcted by
		<% elsif params[:shortlisted] %>
			shortlisted by
		<% else %>
			applied to
		<% end %> 
		<b><%= @jobpost.company %></b> for the role of <b><%= @jobpost.position %></b></p>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Name</td>
				<td>Email</td>
				<% if @jobpost.job_type != 1 && @jobpost.job_type != 4 %>
					<td>College</td>
				<% end %>
				<td>Course</td>
			</tr>
		</thead>
		<tbody>
			<% @applications.each do |a| %>
				<% applicant = Student.find(a.student_id) %>
				<tr>
					<td><%= applicant.first_name+" "+applicant.last_name %></td>
					<td><%= applicant.email %></td>
					<% if @jobpost.job_type != 1 && @jobpost.job_type != 4 %>
						<td>College</td>
					<% end %>
					<td><%= Course.find(applicant.course_id).name %>[<%= Branch.find(applicant.branch_id).name %>]</td>
				<tr>
			<% end %>
		</tbody>
	</table>
<% end %>
<script>
	window.print();
	window.onfocus=function(){ window.close();}
	setTimeout(function () { window.close(); }, 100);
</script>

app/views/jobposts/show.html.erb
<% provide(:title, @jobpost.position.to_s+" | "+@jobpost.company.to_s) %>
<div class="row">
	<% if current_user.user_type == 2 %>
		<%= render '/students/student_sidebar' %>
	<% else %>
		<%= render '/tpos/tpo_sidebar' %>
	<% end %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<div class="show_job_content">
			<div class="job_title">
				<h3><%= @jobpost.company %> hiring <%= @jobpost.position.pluralize %>
					<small>
						[ <%= JobType.find(@jobpost.job_type).name %> <%= " | "+@jobpost.ctc.to_s unless @jobpost.ctc.nil? %> ]
					</small>
				</h3>
			</div>
			<div class="job_info">
				<% if @jobpost.about_company && !@jobpost.about_company.empty? %>
					<div class="desc">
						<div class="desc_title"><h4>About <%= @jobpost.company %></h4></div>
						<div class="about_company">
							<%= simple_format(@jobpost.about_company) %>
						</div>
					</div>
				<% end %>
				<% if @jobpost.job_profile && !@jobpost.job_profile.empty? %>
					<div class="desc">
						<div class="desc_title"><h4>About Position <small>(<%= @jobpost.position %>)</small></h4></div>
						<div class="about_pos">
							<%= simple_format(@jobpost.job_profile) %>
						</div>
					</div>
				<% end %>
				<div class="desc">
					<div class="desc_title"><h4>Eligibility</h4></div>
					<div class="about_eligibility">
						<table class="table table-bordered" id="eligibility_table">
							<thead>
								<tr>
									<th width="200px">Course</td>
									<th>Branch</td>
								</tr>
							</thead>
							<tbody>
								<% @jobpost.courses.each do |c| %>
									<% eligible_branches = Array.new %>
			                        <tr>
			                        	<td class="course_name"><%= c.name %></td>
			                        	<% c.branches.each do |b| %>
			                        		<% eligible_branches.push(b) if @jobpost.branch_ids.include?(b.id) %>
			                        	<% end %>
			                        	<td class="eligible_branches">
				                        	<% eligible_branches.each do |b| %>
				                        		<span class="branch_name"><%= b.name %></span>
				                        	<% end %>
			                        	</td>
			                        </tr>
			                    <% end %>
							</tbody>
						</table>
						<b>Minimum Percentage required : </b><%= @jobpost.percentage_required %> %<br/>
						<b>Eligible batch : </b><%= @jobpost.year_required %>
					</div>
				</div>
				<% if @jobpost.other_requirements && !@jobpost.other_requirements.empty? %>
					<div class="desc">
						<div class="desc_title"><h4>Other Requirements</h4></div>
						<div class="about_req">
							<%= simple_format(@jobpost.other_requirements) %>
						</div>
					</div>
				<% end %>
				<% if @jobpost.instructions && !@jobpost.instructions.empty? %>
					<div class="desc">
						<div class="desc_title"><h4>Instructions From Tpo</h4></div>
						<div class="about_instructions">
							<%= simple_format(@jobpost.instructions) %>
						</div>
					</div>
				<% end %>
				<div class="desc">
					<div class="desc_title"><h4>Event Information</h4></div>
					<div class="relevant_dates">
						<p> <b>Last Date to Apply</b> : <%= @jobpost.last_date.strftime('%A, %B %d, %Y') %></p>
						<p> <b>Date of the Event</b> : <%= @jobpost.drive_date.strftime('%A, %B %d, %Y') %></p>
						<p> <b>Reporting Time</b> : <%= @jobpost.reporting_time %></p>
						<p> <b>Venue</b> : <%= @jobpost.venue %></p>
						<p> <b>Location</b> : <%= Location.find(@jobpost.location_id).location %></p>
					</div>
				</div>
				<div class="actions">
					<% if current_user.user_type == 1 && current_user.id == @jobpost.tpo_id %>
						<%= link_to view_applicants_jobpost_path, :class => "btn btn-default btn-md pull-left" do %>
							<span class="fa fa-th-list"></span> View Applications
						<% end %>
						<%= link_to jobpost_path(@jobpost), method: "delete", 'data-confirm' => "Are you sure you want to delete this post?", :class => "btn btn-danger btn-md" do %>
							<span class="fa fa-close"></span> Delete
						<% end %>
						<%= link_to edit_jobpost_path(@jobpost), :class => "btn btn-primary btn-md" do %>
							<span class="fa fa-edit"></span> Edit
						<% end %> 
					<% end %>
						<% if current_user.user_type == 2 %>
							<% if already_applied? %>
								<span class="btn btn-md btn-success green">
									<span class="fa fa-check"></span> Already Applied
								</span>
							<% elsif !can_apply? %>
								<p class="text-danger">This job is an on-campus opportunity, only the students from <%= @colege.college_name %> can apply.</p>
							<% elsif job_expired? %>
								<p class="text-danger">The Job has expired</p>
							<% elsif is_eligible? %>								
								<%= link_to submit_application_path(jobpost_id: @jobpost.id), :method => :post, :class => "btn btn-md blue" do %>
									<span class="fa fa-sign-in"></span> Apply
								<% end %>
							<% else %>
								<p class="text-danger">You are not eligible to apply for this job</p>
							<% end %>
						<% end %>
				</div>
			</div>
	</div>
	</div>
</div>

app/views/jobposts/view_applications.html.erb
<div class="applications_container">
	<div class="heading_container">
		<h1 class="lead">
			Applications for <%= @jobpost.position %> at <%= @jobpost.company %>
			<small>(Posted on : <%= @jobpost.created_at.strftime('%d %b %Y') %>)</small>
		</h1>
	</div>
	<div class="application_table">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Name</th>
					<th>Course</th>
					<th>College</th>
					<th>Email</th>
					<th>Phone</th>
				</tr>
			</thead>
			<tbody>
				<% @applications.each do |a| %>
					<% applicant = Student.find(a.student_id) %>
					<% course = Course.find(applicant.course_id) %>
					<% branch = Branch.find(applicant.branch_id) %>
					<% college = College.find(applicant.college_id) %>
					<tr>
						<td><%= link_to applicant.first_name+" "+applicant.last_name, applicant %></td>
						<td><%= course.name %><small><%= "["+branch.name+"]" %></small></td>
						<td><%= college.college_name %></td>
						<td><%= applicant.email %></td>
						<td><%= applicant.phone_no %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>