config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/about' => 'welcome#about', as: :about
  get '/login' => 'sessions#new', as: :new_session
  get 'students/populate_branches'
  get 'students/:id/populate_branches' => 'students#populate_branches' 
  get 'jobposts/populate_branches'
  get 'jobposts/:id/populate_branches' => 'jobposts#populate_branches' 
  get 'jobposts/:id/view_applicants' => 'jobposts#view_applicants', as: :view_applicants_jobpost
  get 'jobposts/:id/download_excelsheet' => 'jobposts#download_excelsheet', as: :download_excelsheet_jobpost
  get '/populate_branches'  => 'jobposts#populate_branches'
  get 'jobposts/shortlist_applicant' => 'jobposts#shortlist_applicant'
  get 'jobposts/select_applicant' => 'jobposts#select_applicant'
  get 'students/:id/account_settings' => 'students#account_settings', as: :account_settings_student
  get 'students/:id/my_applications' => 'students#my_applications', as: :my_applications_student
  patch 'students/:id/account_settings' => 'students#update_account'
  get '/students/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_email_availability' => 'all_users#check_email_availability'
  get '/password_resets/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_college_name_availability' => 'tpos#check_college_name_availability'
  get '/tpos/:id/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/:id/check_college_name_availability' => 'tpos#check_college_name_availability'
  patch '/jobposts/:id/:tpo_note' => 'jobposts#tpo_note'

  resources :tpos
  resources :students
  resources :welcome
  resources :sessions
  resources :all_users
  resources :jobposts
  resources :locations
  resources :courses
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:edit, :new, :create, :update]

  delete 'logout' => 'sessions#destroy'
  post 'job_applications' => 'job_applications#create', as: :submit_application
  get '/job_feed' => 'students#job_feed', as: :jobfeed_student
  get '/student_search' => 'tpos#search_students', as: :search_students_tpo
  get '/admin_panel' => 'tpos#admin_panel', as: :admin_panel
  get 'jobposts/:id/print_applicants' => 'jobposts#print_applicants', as: :print_applicants_jobpost
  post '/tpos/activate_tpo' => 'tpos#activate_tpo', as: :activate_tpo

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/tpo.rb
require 'file_size_validator'

class Tpo < ActiveRecord::Base
	
	#self.primary_key = 'email'

	has_many :jobposts, dependent: :destroy #destroy associated job posts when tpo is destroyed

	attr_accessor :remember_token, :activation_token, :reset_token, :image

	mount_uploader :image, ImageUploader

	before_save { self.email = email.downcase.gsub(/\s+/, "") }

	before_save { self.college = college.downcase.titleize.strip.gsub(/\s+/, " ") }

	before_save { self.first_name = first_name.strip.gsub(/\s+/, " ").titleize }

    before_save { self.last_name = last_name.strip.gsub(/\s+/, " ").titleize }

	after_commit :remove_previously_stored_image, on: :update
	
	before_create :update_all_users_table

	before_create :create_activation_digest
	
	validates :email, 
			   presence: true,
			   length: {minimum: 5}, 
			   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
			   uniqueness: { case_sensitive: false } #Note that we have simply replaced true with case_sensitive: false (Rails infers that uniqueness should be true as well.)

	validates :first_name, 
			   presence: true,
			   length: {minimum: 3, maximum: 15}

	validates :college, presence: true, uniqueness: { case_sensitive: false }

	validates :phone_no, numericality: true, length: {maximum: 10, minimum: 8}, allow_blank: true

	validates :password, length: {minimum: 6, maximum: 15}, allow_blank: true

	validates_format_of :image, :with => %r{\.(gif|jpg|png)\z}i, :message => "format is invalid (Only .png, .jpeg & .jpg are allowed)", allow_blank: true

	validates :image, 
                :file_size => { 
                  :maximum => 2.megabytes.to_i 
                } 

	has_secure_password

	def Tpo.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

	def Tpo.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = Tpo.new_token
    	update_column(:remember_digest, Tpo.digest(remember_token))
	end

	# Forgets a user.
	def forget
		update_column(:remember_digest, nil)
	end

	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = self.send("#{attribute}_digest")
		return false if digest.nil?
    	BCrypt::Password.new(digest).is_password?(token)
  	end

  	def activate
	    update_attribute(:activated, true)
	    update_attribute(:activated_at, Time.zone.now)
	  end

  	def send_activation_email
  		UserMailer.account_activation(self).deliver_now
  	end

  	def send_tpo_activation_email
  		UserMailer.tpo_activation(self).deliver_now
  	end

  	def send_mail_to_site_admin
  		UserMailer.new_college_registered(self).deliver_now
  	end

  	def send_welcome_email
  		UserMailer.tpo_welcome_message(self).deliver_now
  	end

  	def create_reset_digest
  		self.reset_token = Tpo.new_token
	    update_column(:reset_digest,  Tpo.digest(reset_token))
	    update_column(:reset_sent_at, Time.zone.now)
  	end

  	def send_password_reset_email
  		UserMailer.password_reset(self).deliver_now
  	end

  # Returns true if a password reset has expired.
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	def create_college(college_name, location_id)
	    new_college = College.new
	    new_college.college_name = college_name
	    new_college.location_id = location_id
	    errors.add(:college, "is already registered with us. You cannot have multiple accounts") if !new_college.save
        new_college.save
    end

    def update_collge
    	college = College.find(self.college_id)
    	college.update_attributes(college_name: self.college.titleize, location_id: self.location_id)
    end

    private

    	def create_activation_digest
    		self.activation_token = Tpo.new_token
    		self.activation_digest = Tpo.digest(activation_token)
    	end

        def update_all_users_table
            new_user = AllUser.new
            new_user.email = self.email
            new_user.first_name = self.first_name
            new_user.last_name = self.last_name
            new_user.college = self.college_id
            new_user.user_type = 1
            errors.add(:email, "is already taken") if !new_user.save
            new_user.save
        end

end

app/controllers/tpos_controller.rb
class TposController < ApplicationController

	before_action :logged_in_user, only: [:edit, :update, :show, :destroy, :index, :admin_panel]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: [:destroy, :index, :activate_tpo, :admin_panel]
	before_action :redirect_if_logged_in, only: [:new, :create]

	include TposHelper

	def new
		@tpo = Tpo.new
	end

	def index
		@tpos = Tpo.all - Tpo.where(admin: true)
	end

	def show
		@tpo = Tpo.find(params[:id])
		if current_user.college_id == @tpo.college_id
			@jobposts = @tpo.jobposts.page(params[:page]).per(50)
		else
			@jobposts = @tpo.jobposts.where("job_type = ? OR job_type = ?", 2, 3).page(params[:page]).per(50)
		end
	end

	def update
		@tpo = Tpo.find(params[:id])
		if @tpo.update_attributes(update_tpo_params)
			@tpo.update_collge
			flash[:success] = "Profile successfully updated"
      		redirect_to @tpo
		else
			render 'edit'
		end
	end

	def create
		@tpo = Tpo.new(tpo_params)
		@tpo.first_name = params[:tpo][:first_name].titleize
		@tpo.last_name = params[:tpo][:last_name].titleize
		college = params[:tpo][:college].titleize
		location_id = params[:tpo][:location_id]
		if @tpo.save && @tpo.create_college(college, location_id)
        	@tpo.update_column(:college_id, College.find_by(college_name: college).id)
			@tpo.send_mail_to_site_admin
			@tpo.send_welcome_email
			flash[:info] = "Thank you for signing up with us. We'll Contact you soon to verify your account"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@tpo = Tpo.find(params[:id])
	end

	def destroy
		tpo = Tpo.find(params[:id])
		college_id = tpo.college_id
		college = College.find(college_id)
		if update_student_colleges(college_id) && college.destroy && tpo.destroy
			flash[:success] = "Tpo & corresponding college deleted"
			redirect_to :back
		end
	end

	def activate_tpo
		tpo_id = params[:tpo_id]
		tpo = Tpo.find(tpo_id)
		tpo.update_attributes(activated: true)
		tpo.send_tpo_activation_email
		flash[:success] = tpo.college+" successfully activated!"
		redirect_to :back
	end
	
	private

		def tpo_params
			params.require(:tpo).permit(:email, :password, :first_name, :last_name, :location_id, :college, :phone_no)
		end

		def update_tpo_params
			params.require(:tpo).permit(:password, :first_name, :last_name, :job_title, :image, :phone_no, :college, :location_id)
		end

		def correct_user
			@user = Tpo.find(params[:id])
			if !(@user == current_user)
				redirect_to root_path
				flash[:danger] = "Action not allowed as you're not the owner of requested profile"
			end
		end

end

app/helpers/tpos_helper.rb
module TposHelper

	def admin_panel

	end

	def search_students
		keyword = params[:search].strip.gsub(/\s+/, " ")
		college_id = current_user.college_id
		@students = Student.search(keyword, college_id)
	end

	def update_student_colleges(college_id)
		other_college_id = College.find_by(college_name: 'Other')
		effected_students = Student.where(college_id: college_id)
		effected_students.each do |e|
			e.update_attribute(:college_id, other_college_id)
		end
	end

	def check_college_name_availability
		college_name = params[:college].downcase.strip.gsub(/\s+/, " ")
		college = College.find_by(college_name: college_name.titleize)
		college = nil if !current_user.nil? &&  !college.nil? && college.id == current_user.college_id
		respond_to do |format| 
			format.json { render :json => college.nil? }
		end
	end

end

app/views/tpos/_college_form.html.erb
<%= form_for(@tpo) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        <%= f.label :email, :class => "control-label" %>
        <%= f.email_field :email, :class => "form-control", :placeholder => "Eg.: username@example.com" %>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <%= f.label :first_name, :class => "control-label" %>
                <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <%= f.label :last_name, :class => "control-label" %>
                <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
            <div class="form-group">
                <%= f.label :college, :class => "control-label" %>
                <%= f.text_field :college, :class => "form-control", :placeholder => "Full Name of College, Location" %>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="form-group">
                <%= f.label :location_id, :class => "control-label" %>
                <%= f.collection_select(:location_id, Location.all, :id, :location, {}, {:class=>'form-control'}) %>
            </div>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :phone_no, :class => "control-label" %>
        <%= f.text_field :phone_no, :class => "form-control", :placeholder => "We'll contact you on this no. for verification" %>
    </div>
    <div class="form-group">
        <%= f.label :password, :class => "control-label" %>
        <%= f.password_field :password, :class => "form-control", :placeholder => "Your Profile Password", :autocomplete => "off" %>
    </div>
    <div class="redirect_links">
    	<%= link_to "SignUp as Student", new_student_path %> | 
        <%= link_to "Already Signed Up?", new_session_path %>
    </div>
    <div class="submit_btn_wrapper btn btn-lg"><span style="visibility:hidden">Sign Up</span>
        <%= f.submit "Sign Up", :class => "btn btn-default btn-lg sign_up_btn" %>
        <span class="hover_span"></span>
    </div>
<% end %>

app/views/tpos/_tpo_sidebar.html.erb
<div class="col-lg-2 col-md-2 col-sm-2 user_content_wrapper tpo_sidebar hidden-xs">
	<div class="user_pic_container">
		<div class="user_pic" style="background:url('<%= @tpo.image_url.nil? ? image_url('default_user.jpg') : image_url(@tpo.image_url.to_s) %>')">

		</div>
	</div>
		<%= link_to @tpo, :class=>"tpo_name" do %>
			<%= @tpo.first_name %> <%= @tpo.last_name %>
		<% end %>
		<% if current_user.user_type == 2 %>
			<div class="tpo_contact_info">
				<span class="divider"></span>
				<p class="text-center"><%= @tpo.email %></p>
				<% unless @tpo.phone_no.nil? %>
					<span class="divider"></span> 
					<p class="text-center"><span class="fa fa-phone"></span> <%= @tpo.phone_no %></p>
				<% end %>
				<!-- Add phone no. -->
				<!--<p><span class="fa fa-phone"></span><br/></p>-->
				<span class="divider"></span>
			</div>
		<% end %>
		<% if @tpo.email == current_user.email %>
			<%= link_to new_jobpost_path, :class => "btn btn-block blue" do %>
				<span class="fa fa-plus"> </span> Post a Job
			<% end %>
		<% end %>
</div>

app/views/tpos/admin_panel.html.erb
<% provide(:title, 'Admin Panel | Simplifica') %>
<div class="main_content">
	<h2 class="text-center">Admin Panel<br/><small>Select an action below to get started</small></h2>
	<table class="table table-bordered table-striped">
		<thead class="text-center">
			<tr>
				<th>Tpos</th>
				<th>Students</th>
				<th>Jobposts</th>
				<th>Courses</th>
				<th>Locations</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= link_to "View all", tpos_path %></td>
				<td><%= link_to "View all", students_path %></td>
				<td><%= link_to "View all", jobposts_path %></td>
				<td><%= link_to "View all", courses_path %></td>
				<td><%= link_to "View all", locations_path %></td>
			<tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td><%= link_to "Add New", new_course_path %></td>
				<td><%= link_to "Add New", new_location_path %></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/tpos/edit.html.erb
<% provide(:title, @tpo.first_name.to_s+" "+@tpo.last_name.to_s+" | Edit Profile") %>
<div class="row">
	<%= render 'tpo_sidebar' %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<div class="tpo_edit_form_container">
			<div class="tpo_edit_form">
				<h3>Update Your Profile</h3>
				<%= form_for @tpo, :html =>{:multipart => true} do |f| %>
				    <%= render 'shared/error_messages', object: f.object %>
				    <div class="form-group">
				        <%= f.label :image, :class => "control-label" do %>
				        	Profile Picture
				        <% end %><br/>
				        <!--<input id="uploadFile" placeholder="Choose File" class="form-control" disabled="disabled" />
						<div class="fileUpload btn btn-primary">
						    <span>Upload</span>
						    <input id="uploadBtn" type="file" class="upload" />
						</div>-->
				        <%= f.file_field :image, :class => "btn-link" %>
				    </div>
				    <div class="form-group">
				        <%= f.label :email, :class => "control-label" %>
				        <%= f.email_field :email, :class => "form-control", :placeholder => "Eg.: username@example.com", :disabled => "true" %>
				    </div>
				    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :first_name, :class => "control-label" %>
                                <%= f.text_field :first_name, :class => "form-control", :placeholder => "Your First Name" %>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="form-group">
                                <%= f.label :last_name, :class => "control-label" %>
                                <%= f.text_field :last_name, :class => "form-control", :placeholder => "Your Last Name"%>
                            </div>
                        </div>
                    </div>
                    <div class="row">
	                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
						    <div class="form-group">
						        <%= f.label :college, :class => "control-label" %>
						        <%= f.text_field :college, :class=>'form-control', :placeholder => "College Name" %>
						    </div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="form-group">
				                <%= f.label :location_id, :class => "control-label" %>
				                <%= f.collection_select(:location_id, Location.all, :id, :location, {}, {:class=>'form-control'}) %>
				            </div>
						</div>
					</div>
				    <div class="form-group">
                        <%= f.label :job_title, :class => "control-label" %>
                        <%= f.text_field :job_title, :class => "form-control", :placeholder => "Your Job Title"%>
                    </div>
                    <div class="form-group">
				        <%= f.label :phone_no, :class => "control-label" %>
				        <%= f.text_field :phone_no, :class=>'form-control', :placeholder => "Phone No." %>
				    </div>
				    <div class="form-group">
				        <%= f.label :password, :class => "control-label" %>
				        <%= f.password_field :password, :class => "form-control", :placeholder => "(Unchanged)" %>
				    </div>
				    <%= f.submit "Update", :class => "btn btn-default btn-lg sign_up_btn pull-right" %>
				    
				<% end %>
			</div>
		</div>
	</div>
</div>
<%= javascript_include_tag 'tpos' %>

app/views/tpos/index.html.erb
<% provide(:title, 'All Tpos') %>
<h1 class="text-center">All Tpos <small>[<%= pluralize(@tpos.count, " Tpo") %>]</small></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email ID</th>
      <th>Phone no.</th>
      <th>College</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% @tpos.each do |tpo| %>
    <tr>
      <td><%= link_to tpo.first_name+" "+tpo.last_name, tpo_path(tpo) %></td>
      <td><%= tpo.email %></td>
      <td><%= tpo.phone_no %></td>
      <td><%= tpo.college %></td>
      <td>
        <% if tpo.activated %>
          Activated
        <% else %>
          <%= link_to "Activate", activate_tpo_path(tpo_id: tpo.id), method: :post %>
        <% end %>
      </td>
      <% if current_user.admin? %>
    	 <td><%= link_to "delete", tpo, method: :delete, data: { confirm: "You sure?" } %></td>
  	  <% end %>
    </tr>
  <% end %>
</table>

app/views/tpos/new.html.erb
<% provide(:title, "College SignUp") %>
<div class="intro_wrapper window_span">
    <div class="intro_wrapper_overlay window_span"></div>
    <div class="container">
        <div class="signup_form_container college_signup form_container curr_active">
            <div class="signup_form form_content animated fadeIn">
            	<p>SignUp as College/TPO</p>
                <%= render 'college_form' %>
           </div>
        </div>
    </div>
</div>

app/views/tpos/search_students.html.erb
<% provide(:title, "Search Results") %>
<div class="student_search_container">
	<div class="heading_container">
		<h1 class="lead">Search Results for - <%= params[:search] %></h1>
	</div>
	<div class="search_results">
		<% if @students.any? %>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Name</th>
						<th>Course</th>
						<th>Branch</th>
						<th>Email</th>
						<th>Phone No.</th>
					</tr>
				</thead>
				<tbody>
					<% @students.each do |student| %>
						<tr>
							<td><%= link_to student.first_name+" "+student.last_name, student %></td>
							<td><%= Course.find(student.course_id).name %></td>
							<td><%= Branch.find(student.branch_id).name %></td>
							<td><%= student.email %></td>
							<td><%= student.phone_no %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% else %>
			<p class="lead text-center">No Results Found</p>
		<% end %>
	</div>
</div>

app/views/tpos/show.html.erb
<% provide(:title, @tpo.first_name.to_s+" "+@tpo.last_name.to_s) %>
<div class="row">
	<%= render 'tpo_sidebar' %>
	<div class="col-lg-10 col-md-10 col-sm-10 main_content">
		<% if @jobposts.any? %>
			<div class="pagination_container">
				<%= paginate @jobposts, :window => 0 %>
			</div>
		  <ul class="list-unstyled jobposts_list">
		  	<li class="lead jobposts_count">
		  		<%= current_user == @tpo ? "My" : @tpo.first_name+"'s" %> Jobposts [<%= @jobposts.count %>]
		  		<small class="pull-right">[<%= @tpo.college %>]</small>
		  	</li>
		    <%= render @jobposts %>
		  </ul>
		  <% else %>
		  	<div class="no_posts_note">
			  	<% if current_user == @tpo %>
			  		<p class="lead">You havn't posted any jobs yet click the button below to create a jobpost</p>
			  		<%= link_to new_jobpost_path, :class => "btn blue btn-lg" do %>
			  			<span class="fa fa-plus"></span> Post a new Job
			  		<% end %> 
			  	<% else %>
			  		<% if current_user.college_id == @tpo.college_id %>
			  			<p class="lead"><%= @tpo.first_name %> hasn't posted any jobs yet.</p>
			  		<% else %>
			  			<p class="lead"><%= @tpo.first_name %> hasn't posted any Off campus or Walk-in opportunties yet.</p>
			  		<% end %> 
			  	<% end %>
			</div>
		<% end %>
	</div>
</div>