config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/about' => 'welcome#about', as: :about
  get '/login' => 'sessions#new', as: :new_session
  get 'students/populate_branches'
  get 'students/:id/populate_branches' => 'students#populate_branches' 
  get 'jobposts/populate_branches'
  get 'jobposts/:id/populate_branches' => 'jobposts#populate_branches' 
  get 'jobposts/:id/view_applicants' => 'jobposts#view_applicants', as: :view_applicants_jobpost
  get 'jobposts/:id/download_excelsheet' => 'jobposts#download_excelsheet', as: :download_excelsheet_jobpost
  get '/populate_branches'  => 'jobposts#populate_branches'
  get 'jobposts/shortlist_applicant' => 'jobposts#shortlist_applicant'
  get 'jobposts/select_applicant' => 'jobposts#select_applicant'
  get 'students/:id/account_settings' => 'students#account_settings', as: :account_settings_student
  get 'students/:id/my_applications' => 'students#my_applications', as: :my_applications_student
  patch 'students/:id/account_settings' => 'students#update_account'
  get '/students/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_email_availability' => 'all_users#check_email_availability'
  get '/password_resets/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/check_college_name_availability' => 'tpos#check_college_name_availability'
  get '/tpos/:id/check_email_availability' => 'all_users#check_email_availability'
  get '/tpos/:id/check_college_name_availability' => 'tpos#check_college_name_availability'
  patch '/jobposts/:id/:tpo_note' => 'jobposts#tpo_note'

  resources :tpos
  resources :students
  resources :welcome
  resources :sessions
  resources :all_users
  resources :jobposts
  resources :locations
  resources :courses
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:edit, :new, :create, :update]

  delete 'logout' => 'sessions#destroy'
  post 'job_applications' => 'job_applications#create', as: :submit_application
  get '/job_feed' => 'students#job_feed', as: :jobfeed_student
  get '/student_search' => 'tpos#search_students', as: :search_students_tpo
  get '/admin_panel' => 'tpos#admin_panel', as: :admin_panel
  get 'jobposts/:id/print_applicants' => 'jobposts#print_applicants', as: :print_applicants_jobpost
  post '/tpos/activate_tpo' => 'tpos#activate_tpo', as: :activate_tpo

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_logged_in_navbar.html.erb
<div class="container">
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".nav-menu">
	        	<span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
        	</button>
			<h1 class="navbar-brand"><%= link_to "sf", root_path %></h1>
			<ul class="nav navbar-nav collapse nav-menu navbar-collapse">
				<% if current_user.user_type == 2 %>
					<li class="pull-left">
						<%= link_to jobfeed_student_path do %>
							<span class="fa fa-home"></span> Home
						<% end %>	
					</li>
					<li class="divider visible-md visible-lg"></li>
				<% elsif current_user.user_type == 1 && current_user.admin %>
					<li class="pull-left">
						<%= link_to admin_panel_path do %>
							<span class="fa fa-home"></span> Home
						<% end %>	
					</li>
					<li class="divider visible-md visible-lg"></li>
				<% end %>
				<li class="pull-left">
					<%= link_to current_user do %>
						<%= image_tag current_user.image_url.nil? ? image_url('default_user.jpg') :  image_url(current_user.image_url.to_s), :alt=>"" %>
						<%= current_user.first_name %>
					<% end %>
				</li>
				<li class="search_form col-lg-6 col-md-4 col-sm-2 col-xs-12">
					<% if current_user.user_type == 2 %>
						<%= form_tag(jobfeed_student_path, :method => "get", id: "search-form") do %>
							<%= text_field_tag :search, params[:search], :placeholder => "Search Jobs by Position, Company or skills", :class => "form-control", :autocomplete => "Off" %>
							<%= button_tag(type: "submit", class: "btn btn-sm") do %>
								<span class="fa fa-search"></span>
							<% end %>
						<% end %>
					<% else %>
						<%= form_tag(search_students_tpo_path, :method => "get", id: "search-form") do %>
							<%= text_field_tag :search, params[:search], :placeholder => "Search students from your college by name or email", :class => "form-control", :autocomplete => "Off" %>
							<%= button_tag(type: "submit", class: "btn btn-sm") do %>
								<span class="fa fa-search"></span>
							<% end %>
						<% end %>
					<% end %>
					<!--<form role="search">
						<input type="text" placeholder="Search Jobs by Position, Location or Company" class="form-control">
						<button class="btn btn-default btn-sm"><span class="fa fa-search"><span></button>
					</form>-->
				</li>
				<li class="dropdown_container"><a href="#"><span class="fa fa-cog"></span> Account <span class="caret"></a>
					<ul class="dropdown_list list-unstyled">
						<li class="arrow_up"></li>
						<% if current_user.user_type == 1 %>
								<li>
									<%= link_to edit_tpo_path(current_user) do %>
									<span class="fa fa-edit"></span> Edit Profile
									<% end %>
								</li>
						<% elsif current_user.user_type == 2 %>
								<li>
									<%= link_to account_settings_student_url(id: current_user.id) do %>
										<span class="fa fa-cogs"></span> Account Settings
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to edit_student_path(current_user), 'data-no-turbolink' => true do %>
									<span class="fa fa-edit"></span> Edit Profile
								<% end %>
							</li>
						<% end %>
						<li class="divider"></li>
						<li>
							<%= link_to logout_path, method: "delete", 'data-no-turbolink' => true do %>
							  <span class="fa fa-power-off"></span> Log Out
							<% end %>
						</li>
					</ul>
				</li>
				<li class="divider pull-right"></li>
				<li class="dropdown_container"><a href="#"><span class="fa fa-language"></span> Opportunities <span class="caret"></a>
					<ul class="dropdown_list list-unstyled">
						<li class="arrow_up"></li>
						<% if current_user.user_type == 2 %>
							<li>
								<%= link_to jobfeed_student_path(job_type: 1) do %>
									<span class="fa fa-institution"></span> On-Campus
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to jobfeed_student_path(job_type: 2) do %>
									<span class="fa fa-building-o"></span> Off-Campus
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to jobfeed_student_path(job_type: 3) do %>
									<span class="fa fa-building"></span> Walk-ins
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to jobfeed_student_path(job_type: 4) do %>
									<span class="fa fa-rocket"></span> Internships
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to jobfeed_student_path(location_id: current_user.location_id) do %>
									<span class="fa fa-map-marker"></span> Nearby 
								<% end %>
							</li>
							<li class="divider visible-xs"></li>
							<li class="visible-xs">
								<%= link_to my_applications_student_path(id: current_user.id) do %>
									<span class="fa fa-list-ul"></span> My Applications
								<% end %>
							</li>
						<% else %>
							<li>
								<%= link_to new_jobpost_path do %>
									<span class="fa fa-plus"></span> Post New
								<% end %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to tpo_path(current_user) do %>
									<span class="fa fa-list-ul"></span> My Posts
								<% end %>
							</li>
						<% end %>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Simplifica | <%= yield(:title) %></title>
	<%= stylesheet_link_tag "style" %>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag  'animate', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'script', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'jquery-validate.bootstrap-tooltip.min', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'signup_validations', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="placement, portal, fresher, jobs, off campus, pool campus, walkins">
	<meta name="description" content="Simplifica is an online placement portal that can be used by different colleges across India">
</head>
<body>
	<div class="body_wrapper">
		<header>
		    <nav class="navbar navbar-default navbar-fixed-top">
		    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary_nav">
		        	<span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		        </button>
		        <div class="container">
		            <h1 class="navbar-brand"><%= link_to "Simplifica", root_path %></h1>
		            <ul class="nav navbar-nav collapse navbar-collapse navbar-responsive-collapse navbar-right" id="primary_nav">
		            	<li>
		                	<%= link_to about_path do %>About Simplifica<% end %>
		                    <span></span>
		                </li>
		                <!--<li>
		                	<a href="#">How it Works?</a>
		                    <span></span>
		                </li>
		                <li>
		                	<a href="#">The Team</a>
		                    <span></span>
		                </li>-->
		                <li>
		                	<%= link_to about_path+'#contact_us' do %>Contact Us<% end %>
		                    <span></span>
		                </li>
		                <li>
		                	<%= link_to "LogIn", new_session_path, class: "login_link" %>
		                	<span></span>
		                </li>
		            </ul>
				</div>
		    </nav>
		</header>
		<div style="position:relative">

			<%= yield %>
			
			<% unless controller_name == 'welcome' && action_name == 'about' %>
				<footer>
					<div class="container">
				        <div class="copyright">copyright &copy; simplifica.co.in</div>
				        <div class="social_links pull-right">
				            <p>Follow Us On</p>
				            <div class="fb"><a href="#">b<span class="fb_hover_span"></span></a></div>
				            <div class="tw"><a href="#">a<span class="tw_hover_span"></span></a></div>
				            <div class="li"><a href="#">j<span class="li_hover_span"></span></a></div>
				        </div>
				    </div>
				</footer>
			<% end %>
		</div>
		<div id="page_loader">
			<div class="page_loader_spinner">
			    <span class="spinner"></span>
			</div>
			<p class="loading_text lead">Loading . . .</p>
		</div>
	</div>
</body>
</html>

app/views/layouts/member_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag 'members', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'logged_in', media: 'all', 'data-turbolinks-track' => true %>

	<%= javascript_include_tag 'members', 'data-turbolinks-track' => true %>
	
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render '/layouts/logged_in_navbar' %>	
	<div class="container content_wrapper" id="big_container">
		<div class="row content_row">
			<div class="col-lg-10 col-md-10 col-sm-12 dynamic_content_wrapper">
				<% flash.each do |message_type, message| %>
					<div class="flash_wrapper">
                		<div class="alert alert-<%= message_type %> activation_alert"><%= message %></div>
                		<span class="terminate" data-dismiss="alert">
                			<i class="fa fa-close"></i>
                		</span>
                	</div>
            	<% end %>
				<%= yield %>
			</div>
			<div class="col-lg-2 col-md-2 col-sm-12 adv_wrapper hidden">
				<div class="advertisement">
					<p>Advertisement</p>
				</div>
				<div class="advertisement">
					<p>Advertisement</p>
				</div>
				<div class="advertisement">
					<p>Advertisement</p>
				</div>
			</div>
		</div>
	</div>
	<div id="page_loader">
		<div class="page_loader_spinner">
		    <span class="spinner"></span>
		</div>
		<p class="loading_text lead">Loading . . .</p>
	</div>
	<footer>
		<div class="container">
			<p>Facing any issues? We're here to help! Drop us a line at <b>support@simplifica.co.in</b></p>
		</div>
	</footer>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>